### ISSUE TITLE
Use earbuds and hats as currency

### ISSUE THREAD

**Issue by arik123** [TF2Autobot/tf2autobot#1012]
It would be nice, if the bot could use earbuds and hats as currency, instead of boring old refined metal and keys.

They are supported by backpack.tf according to `/IGetCurrencies/v1`. Why does the bot not support it then ?

Not supporting these currencies is very unfair, and that is the reason, I think we need this feature.

I will give anyone who helps the community and implements these popular currencies into the bot **50 keys as a reward**.

**Comment by Slips-PC** [comment]
I may be interested in pursuing this for you. Where can I reach out to you to discuss this more?

**Comment by idinium96** [comment]
I think this is unnecessary.
The currency in earbuds and hats was introduced because back in the day, you can only trade 8 to 8 items per trade.
Nowadays, you can trade a lot of items in one trade (within the inventory limit), thus making this feature pretty much uncommon.

Closing this. Thanks for the suggestion btw.
