### ISSUE TITLE
Clarify idinium VPS service privacy remarks

### ISSUE THREAD

**Issue by Slips-PC** [TF2Autobot/tf2autobot#1091]
Hi, I was reading through the wiki page for the VPS pure exchange service you provide and i noticed the below remarks made:

![image](https://user-images.githubusercontent.com/59989951/166574207-b7bffe9a-ab1e-4711-bf9f-49bab49e189b.png)

I use a Hetzner VPS and I can confidently say that there is no way for this to be true. Even *if* they block ssh connections that use passwords and only enable key auth (which i doubt most users will know how to do, and those who *would* know probably can use their own VPS) the person with the account *always* has access via the cloud console itself just by clicking the "terminal" icon (see below)

![image](https://user-images.githubusercontent.com/59989951/166574847-ada1331e-c2e4-47cf-bac0-2c4018cb0808.png)

I would suggest this be further clarified.

**Comment by idinium96** [comment]
Hello,
Yes, it's true, I can connect to the VPS at any moment since I can get their "root password", but if you bought/subscribed to the VPS through me (you can't since you already own one by yourself, refer: [here](https://github.com/TF2Autobot/tf2autobot/wiki/Getting-a-VPS)), I will also include the link to this tip (in the private Discord channel on the TF2Autobot Discord server) to never let myself connect to the server (because the first time setup instructions encourage them to create a new non-root account on their VPS):
![image](https://user-images.githubusercontent.com/47635037/166577356-f5b4bbba-9b75-4724-813f-592cb70b7675.png)

It's totally up to them if they want to follow that tip, and I don't have any interest to get into their VPS without their consent.
Also, I will ask them if they want me to add my public key to their VPS if they need any assistance during the first time setup, and it's totally up to them. If they want to keep my key, that's also up to them.

First-time setup instructions that I sent to each subscriber:
[Setup New VPS steps - username.txt](https://github.com/TF2Autobot/tf2autobot/files/8616777/Setup.New.VPS.steps.-.username.txt)

Let me know if you need any more clarification.

**Comment by Slips-PC** [comment]
It is good that you do provide instructions to do this, however there is still the capability to open up a login shell from the console itself as i pointed out. This does not use SSH and thus bypasses any locks set by sshd. Which may be worth noting.

**Comment by idinium96** [comment]
Yeah, you're right. Didn't know about that, thank you. I will take note of that.
