### ISSUE TITLE
[FIXED] When trying to update bot i get `sh: 1: tsc: not found` and no Dist folder created 

### ISSUE THREAD

**Issue by ScottishPan** [TF2Autobot/tf2autobot#1168]
[FIXED] When trying to update the bot i get `sh: 1: tsc: not found` and no dist folder created.

1. Try to update the bot from the explanation on the wiki
2.Everything goes well untill `npm run build` 
3. You get the error message from above, and there is nod dist folder created
4. When trying to start the bot it says `[PM2][ERROR] Error: Script not found: /storage/emulated/0/download/tf2autobot/dist/app.js`

**Expected behavior**
  Update normally without any problems

**Screenshots**
![Screenshot_20220615_222138](https://user-images.githubusercontent.com/102401755/173908259-de053b26-dfc8-4c40-b331-8e914f36c5f7.jpg)

**Additional context**

Version: 4.14.0

**Comment by carlosliam** [comment]
You probably forgot to run `npm install`. That step is needed before you use `npm run build`.

**Comment by idinium96** [comment]
Are you sure you're "updating" the bot? Because to me, I think you're trying to "install" the bot instead.
The `tsc` is a command for TypeScript, and you might miss a step to install TypeScript.

run `npm install -g typescript@latest` (or `sudo install -g typescript@latest` if you get PERMISSION error), then run that `npm run build` again.
