### ISSUE TITLE
Problem with bot performing !buy & !sell requests.

### ISSUE THREAD

**Issue by MaximilianAdF** [TF2Autobot/tf2autobot#1547]
**Describe the bug**
I'm currently running 4 different bots using TF2autobot and they all seem to have the same problem. Just recently I went over and checked on some of the messages that the bots have received and sent. I see a whole swarm of: "❌ I failed to make the offer! Reason: Failed to load your inventory, Steam might be down. Please try again later. If you have your profile/inventory set to private, please set it to public and try again..". And upon testing it, using !buy !sell myself, it took me on average 15 attempts to get the bot to send the trade. I don't know if there's something wrong with the way I've setup my bots or if this is just common.

**To Reproduce**
* Unsure how to reproduce this behavior.

**Expected behavior**
What's supposed to happen is that the bot sends the !buy or !sell trade on the first request rather than the user having to spam the bot 15 times.

Version: v5.7.0

**Comment by carloslbello** [comment]
This is caused by aggressive Steam rate limiting for the inventory API, which is not something we have control over. There are ways to alleviate this, such as using a rotating proxy service or alternative inventory APIs [(as described in the wiki)](https://github.com/TF2Autobot/tf2autobot/wiki/Alternative-Inventory-APIs). For additional support setting one of these up you can join our Discord: https://discord.gg/4k5tmMkXjB.
