### ISSUE TITLE
Buy listings for killstreak kit are created for wrong item

### ISSUE THREAD

**Issue by Eranikid** [TF2Autobot/tf2autobot#473]
**Describe the bug**
Bot creates `Non-Craftable Killstreak <ITEM> Kit` when selling items, which is correct, but for some reason, when buying items it creates `Non-Craftable <ITEM> Kit`, which incorrect (see missing `Killstreak` in item name)

**To Reproduce**

1. In your bot inventory have some scrap and 1 killstreak kit (for ex. Huo-Lang Heater, `sku=6527;6;uncraftable;kt-1;td-811`)
2. Issue command `!add sku=6527;6;uncraftable;kt-1;td-811&max=2&sell.metal=50&buy.metal=0.11`
3. Go to backpack.tf and search for listings for Huo-Lang Heater KS kit:

**Expected behavior**

**Screenshots and logs**

**Additional context**

Version:

**Comment by idinium96** [comment]
The (Basic) `Killstreak Kit` is special because they have their own specific defindex for a specific item.
https://github.com/TF2Autobot/tf2autobot/blob/4081e2af0ed4591e93bd443e4b2e8f5131fbc2db/src/lib/extend/item/getSKU.ts#L346-L372

For your case, Non-Craftable Huo-Long Heater's sku would be `5798;6;uncraftable;kt-1;td-811`.

There's no fix to this unless you entered the correct sku for it.

**Comment by Eranikid** [comment]
I'm sorry I accidently clicked "Create issue" before finishing it, here is the finished issue: https://github.com/TF2Autobot/tf2autobot/issues/474
